#!/bin/sh

# Execute command and save output and exit status in given directory.
# Resulting output files are:
#    cmdline : Complete command-line and arguments (as a symlink)
#    stdout  : Resulting STDOUT
#    stderr  : Resulting STDERR
#    status  : Command exit status (as a symlink)


PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

usage () {
	echo "Usage: $0 {status_dir} {command} [argument [...]]" 1>&2
	exit 1
}

check_status_dir () {
	[ -d "$STATUS_DIR" ] && [ -w "$STATUS_DIR" ] && return 0
	echo "$0: Invalid status directory '$STATUS_DIR'" 1>&2
	exit 1
}

case $# in
	0|1)
		usage
		# NOTREACHED
		;;
esac

STATUS_DIR="$1"
check_status_dir "$STATUS_DIR"
shift

# Command line.
# File timestamp marks beginning of execution.
# Note use of "$*", not "$@".
ln -sf "$*" "$STATUS_DIR/cmdline"

# Status file is initialized with special value 'undef'.
# Useful to detect if execution may still be in progress, or if exit status
# has not been correctly set.
ln -sf undef "$STATUS_DIR/status"

# Execution, capturing output.
"$@" 1>"$STATUS_DIR/stdout" 2>"$STATUS_DIR/stderr" &
wait %1

# Exit status.
ln -sf "$?" "$STATUS_DIR/status"

# End of process.
exit 0

